/// Flutter icons SubScriptionIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SubScriptionIcons
///      fonts:
///       - asset: fonts/SubScriptionIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SubScriptionIcons {
  SubScriptionIcons._();

  static const _kFontFam = 'SubScriptionIcons';
  static const _kFontPkg = null;

  static const IconData vedio = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doubleup = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dolor = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData croxcircle = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boom = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
